[book]
authors = ["xieby1"]
language = "en"
multilingual = false
src = "docs/"
title = "ğŸªšç¡®å®šæ€§åˆ‡ç‰‡ï¼ˆdeterministic_checkpointsï¼‰â„ï¸"

[output.html]
git-repository-url = "https://github.com/xieby1/deterministic_checkpoints"
